name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install cmake
    - name: Install make
      run: |
        sudo apt-get install make
    - name: Run CMake
      run: cmake -S . -B .
    - name: Running script run_HomeAssign
      run: ./run_HomeAssign
