name: Run Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag home_assign:1
    - name: Run the Docker image
      run: sudo docker run --rm home_assign:1
